server:
  port: 8501

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin:123456@localhost:8101/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
    metadata-map:
      "user.name": admin         #These two are needed so that the server
      "user.password": 123456 #can access the protected client endpoints

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  boot:
    admin:
      client:
        url: http://localhost:8501
#        username: admin
#        password: 123456
        instance:
          prefer-ip: true

---
# admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: 123456

#          name: @artifactId@
#info.tags.security: secured

# 注册给eureka的时候告诉eureka自己的密码
#eureka:
#  instance:
#    metadata-map:
#      "user.name": admin         #These two are needed so that the server
#      "user.password": 123456 #can access the protected client endpoints