spring:
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

#定义详情给服务端和eureka注册中心显示
info:
  app:
    groupId: "@project.groupId@"
    artifactId: "@artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"
    parent-version: "@project.parent.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"

server:
  tomcat:
    uri-encoding: UTF-8