server:
  port: 7301

spring:
  application:
    name: "@artifactId@"
#  cloud:
#    config:
#      name: service-user
#      label: dev
#      profile: dev
#      uri: http://localhost:8851/
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:@project.version@  #${springboot.attribute} @maven.attribute@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8081/eureka

#定义详情给服务端和eureka注册中心显示
info:
  #  version: @project.version@
  app:
    groupId: "@project.groupId@"
    artifactId: "@artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"
    parent-version: "@project.parent.version@"
