version: "3"
services:

  elasticsearch:
    image: elasticsearch:latest
    hostname: elasticsearch
    container_name: elasticsearch
    restart: always
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:latest
    hostname: logstash
    container_name: logstash
    restart: always
    networks:
      - elk
    ports:
      - "9601:9601"
    volumes:
      - ./logstash/config-dir:/config-dir
    command: logstash -f /config-dir
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:latest
    hostname: kibana
    container_name: kibana
    restart: always
    networks:
      - elk
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#  nginx:
#    image: nginx
#    hostname: nginx
#    container_name: nginx
#    restart: always
#    networks:
#      - elk
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/conf/vhost:/etc/nginx/vhost
#      - ./upload/nginx/logs:/opt/nginx/logs
#
#  filebeat:
#    image: filebeat
#    hostname: filebeat
#    container_name: filebeat
#    restart: always
#    networks:
#      - elk
#    volumes:
#      - ./filebeat/conf/filebeat.yml:/filebeat.yml
#      - ./upload:/data/logs
#      - ./filebeat/registry:/etc/registry
networks:
  elk:
    driver: bridge
