filebeat:
  prospectors:
    - paths:
        - "/data/logs/catalina.*.out"
      input_type: filebeat-log
      document_type: tomcat-log
    - paths:
        - "/data/logs/nginx*/logs/*.log"
      input_type: filebeat-log
      document_type: nginx-log

  registry_file: /etc/registry/mark

output:
  logstash:
    hosts: ["logstash:5044"]

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB