server:
  port: 8701

spring:
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"

turbine:
  aggregator:
    cluster-config: default
  app-config: micro-service-user,micro-service-role
  instanceUrlSuffix: /hystrix.stream
  cluster-name-expression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#定义详情给服务端和eureka注册中心显示
info:
  #  version: @project.version@
  app:
    groupId: "@project.groupId@"
    artifactId: "@artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"
    parent-version: "@project.parent.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"