server:
  port: 7101

spring:
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #修改创建的表类型为InnoDB
    open-in-view: true

