server:
  port: 8181

spring:
  application:
    name: @artifactId@

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8081/eureka
zuul:
  routes:
    service-user:
      path: /user/**
      serviceId: micro-service-user
    service-role:
      path: /role/**
      serviceId: micro-service-role
