server:
  port: 8181

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profileActive@
zuul:
  ignored-services: '*' #忽略所有未配置的service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    service-user:
      path: /user/**
      serviceId: micro-service-user
    service-role:
      path: /role/**
      serviceId: micro-service-role
  ratelimit:
    enabled: true
    repository: IN_MEMORY
    behind-proxy: true
    default-policy: #可选 - 针对所有的路由配置的策略，除非特别配置了policies
      limit: 20 #可选 - 每个刷新时间窗口对应的请求数量限制
      quota: 300 #可选-  每个刷新时间窗口对应的请求时间限制（秒）
      refresh-interval: 300 # 刷新时间窗口的时间，默认值 (秒)
      type: URL
    policies:
      user:
        limit: 20
        quota: 300
        refresh-interval: 300
        type: URL

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#定义详情给服务端和eureka注册中心显示
info:
  #  version: @project.version@
  app:
    groupId: @project.groupId@
    artifactId: @artifactId@
    version: @project.version@
    name: @project.name@
    description: @project.description@
    parent-version: @project.parent.version@
