server:
  port: 7201
  ssl:
    key-store: micro-service-business/micro-service-role/target/classes/springboottest.keystore
    key-password: 123456
    key-store-type: JKS
    key-alias: springboot

spring:
#  output:
#    ansi:
#      enabled: always
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"
#  cloud:
#    config:
#      fail-fast: true

feign:
  hystrix:
    #  feign fallback valid
    enabled: true

#定义详情给服务端和eureka注册中心显示
info:
  app:
    groupId: "@project.groupId@"
    artifactId: "@artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"
    parent-version: "@project.parent.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
