server:
  port: 7201

spring:
  output:
    ansi:
      enabled: always
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"

feign:
  hystrix:
    #  feign fallback valid
    enabled: true

#定义详情给服务端和eureka注册中心显示
info:
  #  version: @project.version@
  app:
    groupId: "@project.groupId@"
    artifactId: "@artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"
    parent-version: "@project.parent.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
