version: '3'

services:
  kafka1:
    image: kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
#      KAFKA_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_BOOTSTRAP_SERVERS: 172.119.0.14:9092,172.119.0.15:9092,172.119.0.15:9092
      KAFKA_ZOOKEEPER_CONNECT: 172.119.0.11:2181,172.119.0.12:2181,172.119.0.13:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
#      JMX_PORT: 9999
    volumes:
      - ./kafka1/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      zkka:
        ipv4_address: 172.119.0.14

  kafka2:
    image: kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka2
#      KAFKA_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9093
      #      KAFKA_BOOTSTRAP_SERVERS: 172.119.0.14:9092,172.119.0.15:9092,172.119.0.15:9092
      KAFKA_ZOOKEEPER_CONNECT: 172.119.0.11:2181,172.119.0.12:2181,172.119.0.13:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092
#      JMX_PORT: 9988
    volumes:
      - ./kafka2/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      zkka:
        ipv4_address: 172.119.0.15

  kafka3:
    image: kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9094:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kafka3
#      KAFKA_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9094
      #      KAFKA_BOOTSTRAP_SERVERS: 172.119.0.14:9092,172.119.0.15:9092,172.119.0.15:9092
      KAFKA_ZOOKEEPER_CONNECT: 172.119.0.11:2181,172.119.0.12:2181,172.119.0.13:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9092
#      JMX_PORT: 9977
    volumes:
      - ./kafka3/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      zkka:
        ipv4_address: 172.119.0.16
#  kafka-manager:
#    image: kafka-manager
#    restart: always
#    container_name: kafa-manager-1
#    hostname: kafka-manager-1
#    ports:
#      - "9002:9000"
#    links:            # 连接本compose文件创建的container
#      - kafka1
#      - kafka2
#      - kafka3
#    external_links:   # 连接本compose文件以外的container
#      - zoo1
#      - zoo2
#      - zoo3
#    environment:
#      ZK_HOSTS: 172.119.0.11:2181,172.119.0.12:2181,172.119.0.13:2181
#      KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
##      APPLICATION_SECRET: letmein
##      KM_ARGS: -Djava.net.preferIPv4Stack=true
#    networks:
#      zkka:
#        ipv4_address: 172.119.0.17
networks:
  zkka:
    external:
      name: zk_zkka