server:
  port: 8851
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/winjean/spring/
          search-paths: micro-service-config-center
          username:
          password:
      label: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8811/eureka