spring:
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true #开启config服务发现，既开启集群环境，此开关开启时，client必须使用服务名链接config server。
      server:
        git:
          uri: https://github.com/winjean/micro-service-integration/
          searchPaths: '/micro-service-config/config-info/' #使用应用名称作为搜索路径
          label: master

  boot:
    admin:
      client:
        url: http://localhost:8501
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

