server:
  port: 7101

spring:
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  cloud:
#    config:
#      name: service-user
#      label: dev
#      profile: dev
#      uri: http://localhost:8851/

