server:
  port: 7101

spring:
  application:
    name: "@artifactId@"
  profiles:
    active: "@profileActive@"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  cloud:
#    config:
#      name: service-user
#      label: dev
#      profile: dev
#      uri: http://localhost:8851/
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:@project.version@  #${springboot.attribute} @maven.attribute@
    prefer-ip-address: true
#    metadata-map:
#      "user.name": admin         #These two are needed so that the server
#      "user.password": 123456 #can access the protected client endpoints

    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8101/eureka

#定义详情给服务端和eureka注册中心显示
info:
  #  version: @project.version@
  app:
    groupId: "@project.groupId@"
    artifactId: "@artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"
    parent-version: "@project.parent.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
