server:
  port: 8101

spring:
  profiles: winjean1
#  boot:
#    admin:
#      client:
#        url: http://localhost:8501
#        instance:
#          prefer-ip: true

eureka:
  instance:
    hostname: winjean1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #    fetch-registry: true
    #    register-with-eureka: true
    service-url:
      defaultZone: http://admin:123456@winjean2:8102/eureka/
      register-with-eureka: true
  server:
    #    #eureka server刷新readCacheMap的时间
    response-cache-update-interval-ms: 3000

#    response-cache-auto-expiration-in-seconds: 180
#
#    #启用主动失效，并且每次主动失效检测间隔为3s
#    eviction-interval-timer-in-ms: 3000

---
server:
  port: 8102

spring:
  profiles: winjean2
#  boot:
#    admin:
#      client:
#        url: http://localhost:8501
##        username: admin
##        password: 123456
#        instance:
#          prefer-ip: true

eureka:
  instance:
    hostname: winjean2
    #    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://admin:123456@winjean1:8101/eureka/
      register-with-eureka: true
  server:
    response-cache-update-interval-ms: 3000